redirect pylint and mypy output

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -21,11 +21,15 @@ jobs:
             - name: Pylint
               run: |
                   cd src/
-                  python -m pylint --exit-zero --disable=R,C . > pylint.out
+                  # run pylint with exit code zero so that github actions doesn't
+                  # fail on error. --disable=R,C disables refactor and convention
+                  # warnings which are usually silly. Redirect both stdout and
+                  # stderr to the file pylint.out
+                  python -m pylint --exit-zero --disable=R,C . >pylint.out 2>&1
             - name: mypy
               run: |
                   cd src/
-                  python -m mypy . > mypy.out
+                  python -m mypy . || true >mypy.out 2>&1
             - name: Archive
               uses: actions/upload-artifact@v2
               with:
